[package]
name = "bimble"
version = "0.8.0"
edition = "2021"
authors = ["Virtua-Startups"]
description = "The bimble programming language"

[dependencies]
clearscreen = "3.0.0"
colored = "2.1.0"
regex = "1.10.5"
s_nor = "1.0.1"
