name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Build for Windows
      runs-on: windows-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust for Windows
        uses: actions/setup-rust@v1
        with:
          rust-version: stable-x86_64-pc-windows-msvc

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Package for Release
      run: |
        zip -r bimble_linux.zip target/x86_64-unknown-linux-gnu/release/bimble
        zip -r bimble_windows.zip target/x86_64-pc-windows-msvc/release/bimble.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.1
        release_name: Release v1.0.1
        body: |
          Release notes for v1.0.1

          Added windows, Removed mac, source code, targets folders and integrations and kept bimble the command and changed fork and recreated from ground up and updated repo and added readme file    
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bimble_linux.zip
        asset_name: bimble_linux.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bimble_windows.zip
        asset_name: bimble_windows.zip
        asset_content_type: application/zip
