on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Package for Release (Linux)
      run: zip -r bimble_linux.zip target/x86_64-unknown-linux-gnu/release/bimble
    - name: Upload Artifact (Linux)
      uses: actions/upload-artifact@v3
      with:
        name: bimble_linux
        path: bimble_linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-msvc
    - name: Package for Release (Windows)
      run: zip -r bimble_windows.zip target/x86_64-pc-windows-msvc/release/bimble
    - name: Upload Artifact (Windows)
      uses: actions/upload-artifact@v3
      with:
        name: bimble_windows
        path: bimble_windows.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
    - name: Download Artifacts (Linux)
      uses: actions/download-artifact@v3
      with:
        name: bimble_linux
        path: ./downloads
    - name: Download Artifacts (Windows)
      uses: actions/download-artifact@v3
      with:
        name: bimble_windows
        path: ./downloads
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.1
        release_name: Release v1.0.1
        body: |
          Release notes for v1.0.1
          Added windows, Removed mac, source code, targets folders and integrations and kept bimble the command and changed fork and recreated from ground up and updated repo and added readme file
        draft: false
        prerelease: false
    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./downloads/bimble_linux.zip
        asset_name: bimble_linux.zip
        asset_content_type: application/zip
    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./downloads/bimble_windows.zip
        asset_name: bimble_windows.zip
        asset_content_type: application/zip
